### ISSUE TITLE
Links currently open webpages in the same tab

### ISSUE THREAD

**Issue by mwatkins1970** [StampyAI/stampy#249]
A site user pointed out it would be better if links opened new tabs.

**Comment by ProducerMatt** [comment]
Thank you for opening an issue! However, this is the backend repo, please open an issue in the UI repo instead: https://github.com/StampyAI/stampy-ui/issues Sorry for the confusion.

**Comment by Aprillion** [comment]
Actually, no need to re-open in UI repo - if I remember correctly, this was discussed and declined because:

* people who want to open links in new tabs can use default browser action to open links in new tabs (wheel button click, or Ctrl+click, or right click and choose from context menu)
* people who want the default browser behaviour for clicking links (open in the same tab, then press back button when returning to previous page) wouldn't have that option if we changed the default click behaviour
